name: Install Dependencies
inputs:
  working-directory:
    required: true
    type: string

runs:
  using: composite
  steps:
    # Setup Bun
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    # Install Dependencies
    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: bun install --frozen-lockfile
