name: Install Dependencies
inputs: 
    working-directory:
        required: true
        type: string
        
runs:
    using: composite
    steps:
        - name: Install Dependencies
          working-directory: ${{ inputs.working-directory }}
          shell: bash
          run: bun install --frozen-lockfile
