services:
    # Mongo Database
    mongo:
        image: mongo:latest
        container_name: lilify-db
        ports:
            - "27017:27017"
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db

    # Mongo Express UI
    mongo-express:
        image: mongo-express:latest
        container_name: lilify-db-ui
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            # Login credentials for the web browser popup
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        depends_on:
            - mongo

    # API 
    express:
        build:
            context: ./
        develop:
            watch:
            # Sync source files without rebuild
            - path: ./
              action: sync
              target: ./app/
              ignore:
              - node_modules/
            # Sync source files without rebuild
            - path: package.json
              target: ./app/package.json
              action: rebuild
        container_name: lilify-api
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - mongo

# According Volumes
volumes:
    mongo-data:
