name: API CI

on:
    workflow_call:
        secrets:
            MONGO_URI:
                required: true

jobs:
    test-and-verify:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:latest
                ports:
                    - 27017:27017

        steps:
            # Checkout Code
            - name: Checkout Code
              uses: actions/checkout@v5
            # Setup Bun Environment
            - name: Setup Bun Environment
              uses: ./.github/actions/setup-bun
            # Install Dependencies
            - name: Install Dependencies
              uses: ./.github/actions/install-deps
              with:
                working-directory: ./packages/api
            # TypeScript Check
            - name: TypeScript Check
              uses: ./.github/actions/tsc-check
              with:
                working-directory: ./packages/api
            # Test Check 
            - name: Test Check 
              uses: ./.github/actions/test
              with:
                working-directory: ./packages/api
