name: API CI

on:
    workflow_call:
        secrets:
            MONGO_URI:
                required: true

jobs:
    test-and-verify:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:latest
                ports:
                    - 27017:27017

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Setup Bun Environment
              uses: ./.github/actions/setup-bun
            - name: Install Dependencies
              uses: ./.github/actions/install-deps
              with:
                working-directory: ./api
            - name: TypeScript Check
              uses: ./.github/actions/tsc-check
              with:
                working-directory: ./api
            - name: Test Check 
              uses: ./.github/actions/test
              with:
                working-directory: ./api

            # - name: Unit-Tests
            #   env:
            #       MONGO_URI: mongodb://localhost:27017/lilify_test
            #   run: bun test
