name: Build API
on:
    workflow_call:

jobs:
    build-api:
        runs-on: ubuntu-latest
        steps:
            # Checkout Code
            - name: Checkout Code
              uses: actions/checkout@v5
            # Setup Bun Environment
            - name: Setup Bun Environment
              uses: ./.github/actions/setup-bun
            # Install Dependencies
            - name: Install Dependencies
              uses: ./.github/actions/install-deps
              with:
                  working-directory: ./api
            # Build Docker Image
            - name: Build Docker Image
              run: docker build -t lilify ./api
