name: Frontend
on:
    workflow_call:

jobs:
    test-and-verify:
        runs-on: ubuntu-latest
        steps:
            # Checkout Code
            - name: Checkout Code
              uses: actions/checkout@v5
            # Setup Bun Environment
            - name: Setup Bun Environment
              uses: ./.github/actions/setup-bun
            # Install Dependencies
            - name: Install Dependencies
              uses: ./.github/actions/install-deps
              with:
                working-directory: ./packages/frontend
            # Test Check
            - name: Test Check
              uses: ./.github/actions/test
              with:
                  working-directory: ./packages/frontend
