name: Frontend
on:
    workflow_call:
      
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v5
          - name: Setup Bun
            uses: ./.github/actions/setup-bun
          - name: Install Dependencies
            run: bun install --frozen-lockfile