name: Lint
on:
    workflow_call:
      
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Bun Environment
            uses: ./github/actions/setup-bun
          - name: Install Dependencies
            uses: ./github/actions/install-deps
            with:
                working-directory: ./
          - name: Lint Check
            run: bunx biome ci .
 