name: Lilify CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        uses: ./.github/workflows/ci-lint.yml
    api:
        needs:
            [lint]
        uses: ./.github/workflows/ci-api.yml
        secrets:
            MONGO_URI: ${{ secrets.MONGO_URI }}
    build-api:
        needs: [api]
        uses: ./.github/workflows/ci-build-api.yml
    frontend:
        needs:
            [api]
        uses: ./.github/workflows/ci-frontend.yml
